### PR TITLE
Making that React JS work beautifully with Baobab :-)

### PR DESCRIPTION
**Pull request by christianalfoni**
Hi,

There are a few changes here. Let me summarize:

1. Fixed so that mixins added will run after the Baobab mixin. This allows mixins to point to the cursors etc. that the Baobab mixin adds. This gives a lot more power to change the behavior of components

2. The components will now get the state of the cursors added to the state object. The reason for this is that the state object is what React JS uses to evaluate rendering. Now the shouldComponentUpdate and PureRenderMixin are useless and you either have to prevent all rendering (which it actually does now using the PureRenderMixin) or allow rendering and nested rendering all the time. The fix by adding all Baobab state to component state fixes use of PureRenderMixin

3. Added an option to include the React JS immutable helper. This in combination with the moving of cursor state to component state gives you full control of rendering

4. Some README updates

5. Tests of course

Okay, I hope you like!

I have some comments in the 6b11574 commit :-)

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, sorry for the late answer. There are some things I do not understand concerning your PR. I might cherrypick some of your commits so I can integrate it partially for the time being.

1. Good point. I shall integrate this part.
2. This seems correct and advisable indeed. Let me just document myself a bit better concerning React so I can reflect on this properly.
3. I don't get your point here. Doesn't the `tree.update` and `cursor.update` already fit your needs?

**Comment by christianalfoni** [comment]
Hi @Yomguithereal , no worries on late response :-)

I should have explained point 2/3 better, sorry about that. What you want to achieve with React JS is that the component only renders if there is a change in the data model it is based on. Currently the implementation uses "forceUpdate" to render components. The problem with this is that there is no way to avoid rendering when not needed. So in scenarios where you have components that listens to a cursor/tree and the component has a large subtree of components, they will all render, no matter what you do. If one of the subtree components also listens to an update it will render a second time, and so will all its sub components.

By moving the state value of a cursor to the state of the component you are able to control its rendering with "setState" instead. That is something you can control, specifically with the "shouldComponentUpdate" method, which "PureRenderMixin" uses. So that is the first part of the solution.

The second part is when you listen to cursors that holds an object or array. The "PureRenderMixin" is not able to verify a change in the value as it will always be the same array or object, preventing the component from rendering the updates. You can solve this by turning on cloning, but then the component will always render when there is an update, as the array/object will always be different. What you want is the reference on arrays/objects to change when there actually has been a change and that is what "React.addon.update" solves.

So to summarize the flow where you have one component listening to a tree that holds two different array (items and todos):

Push object to array on cursor "items" -> tree emits "update" -> component checks the reference of current "items" array on the state with the new reference coming from the cursor -> It renders because the reference has changed

Push object to different array on cursor "todos" -> tree emits "update" -> the same component again checks for reference change on the "items" array -> It does not do a new render because the "items" array reference has not changed

I hope the summary was okay :-) React JS does recommend using the "addon.update" method in combination with the PureRenderMixin to optimize rendering, so that is basically what I am trying to let Baobab do. [http://facebook.github.io/react/docs/update.html](http://facebook.github.io/react/docs/update.html)

**Comment by ArnoBuschmann** [comment]
Thanks @christianalfoni for your explanations.

Right now I wonder, how "computed data" fits into the picture.

Facebook suggests to put computed data to the render() method:

http://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#what-shouldnt-go-in-state

But I think that might be not the best place as it is redundant, if for example two react components need the same computed data.

Now could we handle computed data by
-> not putting the computation into the render() method
-> and not declaring "computed state" in Baobab either
-> but having a method that returns a computed value and calling this method in render()?

Am I right to say, that even if the component doesn't need the cursors' data itself, just the computed data, rerendering would work correctly as long as I pass the cursor (the computed data is relying on) to the react component?

**Comment by Yomguithereal** [comment]
@christianalfoni,

If I understand correctly, moving the cursor data to state has something to do with the prevention of nested renders? I see why `forceUpdate` is bad and I will indeed follow your PR concerning the move of cursor data to state.

What I don't get is why you need to check the state's differences when using baobab. A cursor will never trigger an update event if its data has not been changed. The only case is when you tell a cursor to update with its already current value (`cursor.edit(cursor.get()` for instance).

So normally, the part of the state you want to check is only the one which is not relative to your baobab's data.

Are you, in your use case, using a single master component listening to tree updates and not binding key components to cursors?

**Comment by christianalfoni** [comment]
Hi, yeah, great question!

Lets look at an example. I have 50 components in my application. They are nested in 10 levels. At level 2 I am listening to a specific cursor. Whenever that cursor changes all levels from 3-10 will actually do a render because the specific level 2 component needed to do a render.

To fix this, each component at level 3 will do a "Do I need to render check". They do this by checking their state property (PureRenderMixin). If Baobab saves the state of a cursor on the state object of the component they will be able to check if the state actually has changed, and thus preventing this cascading of renders down the level 3-10.

I think I would get my thoughts out better with a drawing or something. Let me know if my explanation sucks and I will be happy to create a drawing :-)

**Comment by Yomguithereal** [comment]
Ok, so if I understand correctly, the problem at hand here is that the fact that baobab is not totally immutable and keeps references effectively preventing the `shouldComponentUpdate` of the `pureRenderMixin` from perform its shallow comparison on the state because of the continuous reference.

I think this is indeed a very important thing to figure out concerning the future of baobab.

The thing is I really love immutability and thinks baobab should be treated "as" immutable but don't want to march completely towards it mostly for perf and lib size reasons (facebook's `immutable` is fine but a size hulk for instance).

Let's consider the following: what if boabab were to perform internally what the react update addon does? I.e. shifting only the references affected by your update so that the equality checks can be handled gracefully afterwards?

---

On a different topic, the UIs I build does not often require top-level components to handle cursor data. Rather the leaf components do. But my UIs are rarely very complex and can 1) consider rendering as nearly zero-cost operations and 2) don't have complex sets of nested components.

Your experience with baobab is therefore more than valuable.

**Comment by christianalfoni** [comment]
Hi again :-)

1. It would be great if Baobab does what "React.addon.update" does out of the box. I think it is an awesome idea!

It can be difficult to understand the benefits of immutability with React JS. Also the "addon.update" API is an object with special properties ($push, $set etc.), which can be a bit "off putting", as we usually think of APIs as methods. I think those two things combined makes it overlooked very easily. With Baobab and its "select" API, you can easily hide this stuff behind the existing "push", "set" etc. Giving developers a common method API and still get the optimization of immutability with React JS.

I think it is a great idea :-)

2. I first got into flux when I was building www.jsfridge.com. It is a quite a complex UI and it has lots of application state. I often think of that project when working on flux ideas and contributions. Very glad I can share those experiences in a project like this.

3. #65 was based on the idea that Baobab state values was not immutable. But generally with flux you use IDs to reference objects, so when going all immutable it might be an idea to investigate selectors that helps with that pattern. For example:

```javascript
var tree = new Baobab({
  items: []
}, {
  mixins: [React.addon.PureRenderMixin],
  immutable: true
});

tree.select('items', 0) // by index
tree.select('items', {id: 1}) // By prop comparison. Much like underscores "findWhere"
``` 

What do you think?

**Comment by Yomguithereal** [comment]
Good afternoon.

1. I will switch to the react update behaviour soon.
2. I will try to cherrypick the first commit of this PR.
3. I will enable the `state.cursor` (but I need first to solve #44 before so I can simplify the mixin).
4. I like the select by prop comparison or function and this is what I was foreseeing through #75). I just need to see whether it can be done without too much ado perf-wise.

**Comment by christianalfoni** [comment]
Good morning!

1. Yeah, an "immutable" option would be nice I think. It is very React JS specific, at least currently, so forcing it might give problems in other use cases

2. Cool

3. Sweet!

Let me know if you would like a new pull request for the mixin fix and/or if I can help you out with any of the other issues.

**Comment by Yomguithereal** [comment]
2. is done. Moving to other points of the list.

**Comment by christianalfoni** [comment]
Well, that was fast :-)

This is the functionality of the React JS immutability helpers. I have strike through the ones I suppose already works with immutability?

~~{$push: array} push() all the items in array on the target.~~
~~{$unshift: array} unshift() all the items in array on the target.~~
**{$splice: array of arrays} for each item in arrays call splice() on the target with the parameters provided by the item.**
~~{$set: any} replace the target entirely.~~
**{$merge: object} merge the keys of object with the target.**
~~{$apply: function} passes in the current value to the function and updates it with the new returned value.~~

It would be nice to get the splice especially, but without the really cumbersome API from Facebook.  It would be a lot better to just replicate the native API, but maybe consider having the "findWhere" possibility here too?

```javascript
tree.select('items').splice(0, 1);
```

**Comment by Yomguithereal** [comment]
Sorry, I was a bit misleading, I mixed 1 with 2. I only cherrypicked your commit for the time being ^^.

**Comment by christianalfoni** [comment]
Ah, hehe ;-)

**Comment by Yomguithereal** [comment]
3. is now done.

**Comment by Yomguithereal** [comment]
I am listing commands requiring a reference shift:

* $push
* $unshift

The other are already shifting the reference aren't they?

**Comment by christianalfoni** [comment]
This is awesome, looking forward to the release, testing it out!

You are referring to $splice and $merge?

**Comment by Yomguithereal** [comment]
`1.` is now done and affected references will be shifted at update when activating the `shiftingReferences` option. Baobab's update behaviour shall then be identical to react update's one.

I will add more commands later.

**Comment by christianalfoni** [comment]
Awesome! You have a new release now? I see npm does not have a new version. No worries, I can just play around with the version on the repo.

**Comment by Yomguithereal** [comment]
I want to wrap some more updates before making a npm release. But it will arrive soon.

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, the `0.3.0` version has been released on npm. You can find the changelog [here](https://github.com/Yomguithereal/baobab/releases/tag/0.3.0).

I am therefore closing this PR :)

**Comment by ismael-hompanera** [comment]
Hello everyone!

Can anyone help me with this? I want to remove two items from a Baobab Object at the same time. After several seconds I need to remove some items but when I remove the first one, the index is updated and then the second item is not found. Help me please!!

**Comment by Yomguithereal** [comment]
Hello @ismael-hompanera. As for raw JavaScript arrays, you should unset array items in descending order: 

```js
var a = ['one', 'two', 'three'];
// Let's say I want to drop 'one' & 'three'
// -> I need to drop the 0 & 2 indexes

// The following will not work because the list will change and when we arrive at 2, it does not exist anymore and has become 1
a.splice(0, 1);
a.splice(2, 1);

// Just delete the items in reverse index order:
a.splice(2, 0);
a.splice(0, 1);
```

If you have a problem because the second unset might happen several times after the first one, then it's another problem that can be solved differently. But for now, does this solve your problem?

**Comment by ismael-hompanera** [comment]
Thanks @Yomguithereal , finally I resolved it with unset(element).

**Pull request closed without merging**
