### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by christianalfoni**
Okay, this looks scary! :-)

I think this is a really important change. People visiting the REPO today does not really get an introduction to what Baobab is and especially why you would want to use it. The README has become too big.

So I created a WIKI that has a more "how to use" perspective, than a "how it is built" perspective. I think that is important to give developers a good intro. I also expand on this to give introductions to patterns and how to solve specific scenarios.

I also included the article I wrote as it has gotten really good feedback, even [dailyjs](http://dailyjs.com/) mentioned it being a good introduction to Baobab.

To me this LIB has been as big as the React JS release itself. It truly is the "next generation" of application architecture and we have to make it easy for other developers to understand what this is all about :-)

I have also reworked a lot of the examples to be more app related. I hope you like :-)

### CODE REVIEW

**Comment by lucasmreis** [comment]
First of all, thank you for the amazing library!

I really think the concept of a centralized state object simplifies a lot the app architecture. Simplify in the powerful way [described by Rich Hickey](http://www.infoq.com/presentations/Simple-Made-Easy). We are using in production on a big project, and we can easily fell the benefits. So I agree that you should "sell" the library as an architecture solution!

I even wrote a [post about this](http://lucasmreis.github.io/blog/a-more-functional-approach-to-angular/) in my blog (first post :) ), in which I use a more naive implementation of a unique State object.

All the frameworks/libraries I found were based on React, and Baobab is the first that is framework-agnostic. This is a good thing, since we use Angular :) I'll try to implement the same sample app using Baobab, and I can come back with the experience.

One more time, thank you very much for the awesome work!

**Comment by christianalfoni** [comment]
Hi @lucasmreis ,

Thanks for sharing that video, really inspiring stuff :-)

It would actually be great to have a similar "Angular practices" on the wiki, like the "React JS practices" now. Maybe you want to share your experiences there? I have not personally used Baobab with Angular, but I have been working on [flux-angular](https://github.com/christianalfoni/flux-angular) and have the experience that FLUX like architectures does indeed help out Angular developers :-)

**Comment by lucasmreis** [comment]
:+1: as soon as I have something to share with you I come back!

**Comment by jondlm** [comment]
I disagree with the premise for this PR. I was introduced to Baobab from a co-worker posting a link straight to the readme. It wasn't hard for me to quickly realize how useful the library is for global state management. It would be a shame to take such well written documentation off the front page.

**Comment by christianalfoni** [comment]
@jondlm Good thing we got an other perspective on this :-) Yeah, removing the readme content is a bit drastic, though I think it is important to acknowledge that developers comes to the repo with different from different angles. Like you I instantly recognized how I could use Baobab with my React JS application, it was the missing piece, though did I not have that experience it might have been difficult to understand why I would need the lib. From that angle I think the readme is more confusing than helpful.

So maybe a good compromise here is to just link to the Wiki on the existing readme?

**Comment by Yomguithereal** [comment]
@christianalfoni, this is probably what I will do soon. I will keep the README upfront and link to the wiki (thanks for it by the way :) )for more specific matters. I need some time however to read the wiki and adjust things if needed.

**Comment by christianalfoni** [comment]
:+1:

**Comment by jondlm** [comment]
That seems like a great way to proceed. Thanks for the hard work all around!

**Comment by Yomguithereal** [comment]
I am closing this but this does not mean I finished reading the wiki :). You guys did a huge work on it and now with the v1 I shall peruse it and update it so it can remain a fine tool.

**Pull request closed without merging**
