### PR TITLE
Supporting TypeScript

### PR DESCRIPTION
**Pull request by AlbertZheng**
In order to support TypeScript, I changed below. Please review.
1. Upgraded babel from 5.6.14 to the newest 6.6.4, so that the generated ES2015 codes by babel can compatibly work with codes generated by TypeScript compiler and webpack. 
2. Added the TypeScript Definitely Typed File `index.d.ts`.
3. Added `index.js` for working in with `index.d.ts`
4. Modified `package.json` correspondingly.

BTW, I fixed a bug in `watcher.js` which emitted a event without carrying the event object.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @AlbertZheng. Thanks for you work! This seems like a nice and awaited enhancement. I want to merge your PR but it seems that when updating to Babel 6 you broke the test command requiring babel's register hook. Can you fix it so I can merge please?

If you don't know how, just tell me & I'll merge then fix the issue plus one another concerning ES6 exports and backward compatibility with CommonJS.

**Comment by AlbertZheng** [comment]
> but it seems that when updating to Babel 6 you broke the test command requiring babel's register hook. Can you fix it so I can merge please?
> 
> If you don't know how, just tell me & I'll merge then fix the issue plus one another concerning ES6 exports and backward compatibility with CommonJS.

@Yomguithereal Sorry, I checked the CI errors, but I amn't familiar with babel hook. Could you please merge the PR then fix this issue? Thanks in advance.

**Comment by AlbertZheng** [comment]
> Update the README.md for TypeScript usage.

@Yomguithereal I added a new commit for updating the `README.md` for TypeScript usage.

**Comment by Yomguithereal** [comment]
Thanks @AlbertZheng. I'll need to find some time to merge the PR and publish a release however. It should be done soon, don't worry.

**Comment by Yomguithereal** [comment]
Also, don't you need to indicate the `typings` in the package.json file?

**Comment by AlbertZheng** [comment]
> Also, don't you need to indicate the typings in the package.json file?

It doesn't need the `typings` indication in the `package.json` of Baobab user's project, and also doesn't need an individual `typings.json` in user's project. Just `npm install baobab` like before, then the compiler of TypeScript will search the `node_modules/baobab` and find out the `index.d.ts` according the indication of 'main: ./index.js' in the `package.json` of Baobab package.

BTW, the typings has been deprecated by the newest TypeScript 2.x, instead of, using such as 'npm install @types/react' which will install the TypeScript Definitely Typed File into `node_modules/@types/react` if this package doesn't distribute the official .d.ts files together with its npm publication.

**Comment by Yomguithereal** [comment]
Not forgetting you. Just trying to find someone knowledgeable in TypeScript to help me review the code.

**Comment by AlbertZheng** [comment]
@Yomguithereal I had added a section to describe the TypeScript usage in README.md of this [PR commit](https://github.com/Yomguithereal/baobab/pull/464/commits/fbc76969eae12a55669fe23954b39c9279400fdd). 

The first step for using this TypeScript supporting PR is to use `node` module resolution option in the TypeScript compiler config file `tsconfig.json` of user's project, and most users are using this option. 

> 1. Checking the `tsconfig.json` of your TypeScript project, and make sure the `compilerOptions` is using `node` module resolution.
> 
> ```js
> "compilerOptions": {
>   ...
>   "moduleResolution": "node",
>   ...
> }
> ```

**Comment by luccitan** [comment]
Hi,

I am not a TypeScript user, but I did some changes so that : 
- the scripts use the opt-in module `babel-register`, since there is no more monorepo `babel`
- the export syntax is updated to fit the new one used in Babel 6
For example : `monkey` in `import Baobab, {monkey} from '../../src/baobab'` from `test/suites/baobab.js` was undefined since importing/exporting changed its way

It is available in [this commit](https://github.com/luccitan/baobab/commit/4b2e552f54d941dadb9fbf19ba299f6e62301d4c). You can either update this PR or push one I create

**Comment by Yomguithereal** [comment]
Sorry everyone for lagging on this PR. But the upside is the lib now has type declaration (some years later) :)

**Pull request closed without merging**
