### PR TITLE
chore: Updated Babel Dependencies

### PR DESCRIPTION
**Pull request by anthony-redFox**

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @anthony-redFox. Why did you drop the loose transpilation? It was there for bundle size & performance.

**Comment by anthony-redFox** [comment]
@Yomguithereal  you right, I missed "loose" option. fixed

**Comment by Yomguithereal** [comment]
And I don't remember correctly but won't the `env` preset compile for node's version hence making the build unusable on currently supported browsers?

**Comment by anthony-redFox** [comment]
By default uses babel-preset-es2015, babel-preset-es2016, and babel-preset-es2017 together
https://babeljs.io/docs/plugins/preset-env/

It is support node and browsers and currently we also transpile code to ES5 version.

**Comment by anthony-redFox** [comment]
@Yomguithereal  ```Env ``` just encapsulate babel-preset-es2015, babel-preset-es2016, and babel-preset-es2017 depend of version node or browsers. Which browser version are you care we will not support?

**Comment by Yomguithereal** [comment]
ES2015 should be the only thing to transpile because I don't use later features. Built version should support at least IE9 if I remember correctly.

**Comment by anthony-redFox** [comment]
@Yomguithereal  done. Replaced on babel-preset-es2015 package.

**Comment by Yomguithereal** [comment]
Thanks @anthony-redFox. Merging now.

**Pull request merged**
