### PR TITLE
Fixed latency issues with type checking

### PR DESCRIPTION
**Pull request by christianalfoni**
Hi there,

I thought I could create a pull request for this. I did not want to remove topology completely I just added a custom type checker for Baobab and let all of Baobab use that internally.

So there is no removed code here, only replaced checks. Now we are actually down to 2 ms, where it was at over 600ms.

I thought this could be a good first iteration?

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Thanks @christianalfoni! I will give it a look tonight.

**Comment by christianalfoni** [comment]
Cool :-)

I also run the new version on our framework which has become quite huge, not experienced any problems. That in addition to tests going green of course :-)

Do not feel bad if you think its too much to change or if it is changed not to your liking. I just had to check how much performance I could get out of it.

**Comment by Yomguithereal** [comment]
Merged. I might just change some little thing in type.js to comply with my OCDs.

`typology` will be removed in favor of a validate routine that can be provided by the user.

I will probably release a `0.3.2` version of the lib before introducing breaking changes.

**Comment by christianalfoni** [comment]
haha, I know the feeling ;-) Great, thanks for the merge!

**Pull request merged**
