### PR TITLE
Using Baobab 2.5.1 is causing babel to fail #501 Fixed

### PR DESCRIPTION
**Pull request by anthony-redFox**
After update babel package added default export.
https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
https://github.com/babel/babel/issues/2212

### CODE REVIEW

**Comment by anthony-redFox** [comment]
@Yomguithereal please, take a look

**Comment by Yomguithereal** [comment]
@anthony-redFox I think I prefer to drop the `export default class Baobab` in `index.js` and switch to `module.exports = Baobab` in the same file to save us the dependency. What do you think?

**Comment by Yomguithereal** [comment]
Sorry @anthony-redFox. I will close this PR, push a commit and release a version asap so people can continue to install the lib unbothered. Thank you very much for your work. Sorry for not being able to merge.

**Comment by anthony-redFox** [comment]
@Yomguithereal  it is ok. After your fix ES6 Modules doesn't work, but in version 2.5.1 it worked. 

So we need to discuss how to support ES6 Modules for baobab.

**Comment by Yomguithereal** [comment]
Indeed. What do you propose? Should we use one of the package.json fields such as `js:next` `module` and such?

**Pull request closed without merging**
