### PR TITLE
support objects created with Object.create(null)

### PR DESCRIPTION
**Pull request by fmal**
Currently Baobab doesn't work well with objects created like `Object.create(null)` for dictionaries due to use of `.hasOwnProperty()` on them. By using `hasOwnProperty` from another Object we can solve this problem.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @fmal. Can you run some minimalist benchmarks & check whether this impairs performance or not?

**Comment by fmal** [comment]
Hi @Yomguithereal, i have created some test case here: https://jsperf.com/b-cloner. Not sure how correct this is, but seems like the original cloner performs a bit faster in most cases (though the difference is neglible).

**Comment by Yomguithereal** [comment]
The difference is negligible indeed. Let me review the PR & make some remarks so we can merge it :).

**Comment by Yomguithereal** [comment]
Ok, correct me if I'm wrong, but shouldn't you also use your function in the `freezer` one?

**Comment by Yomguithereal** [comment]
Can I merge?

**Comment by fmal** [comment]
yes please :) and thanks for the feedback!

**Comment by Yomguithereal** [comment]
Just released v2.3.4 on npm with your patch. Thanks @fmal.

**Pull request merged**
